name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Check required Node.js version
        id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - name: Install Node.js ${{ steps.nvmrc.outputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'

      - name: Install dependencies
        run: |
          yarn set version latest --yarn-path
          yarn install --frozen-lockfile

      - name: Run linters
        run: yarn lint

      - name: Run tests
        run: yarn test
