name: Publish package

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Enable Corepack before setting up Node
              run: corepack enable

            - name: Check required Node.js version
              id: nvmrc
              uses: browniebroke/read-nvmrc-action@v1

            - name: Install Node.js ${{ steps.nvmrc.outputs.node_version }}
              uses: actions/setup-node@v3
              with:
                  node-version: '${{ steps.nvmrc.outputs.node_version }}'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: |
                  yarn set version latest --yarn-path
                  yarn install

            - name: Build
              run: yarn build

            - name: Publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
